name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Verificar conectividad a internet
      - name: Verify internet connectivity
        run: |
          echo "Verificando conectividad a internet..."
          curl -I https://www.google.com  # Verifica si se puede hacer una solicitud HTTP
          
          # También puedes usar el comando 'ping' si prefieres verificar la conectividad ICMP
          # ping -c 4 google.com

      # Paso 3: Configurar Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Paso 4: Construir y desplegar la aplicación
      - name: Build and Deploy
        run: |
          docker-compose up --build -d

      # Paso 5: Verificar que los contenedores están en ejecución
      - name: Verify containers are running
        run: |
          docker ps

