name: Deploy App with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start containers
        run: |
          docker compose up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Esperando 10 segundos para que los servicios estén listos..."
          sleep 10

      - name: List running containers
        run: docker ps

      - name: Test HTTP response
        run: |
          curl --max-time 20 http://localhost:3000 || echo "La aplicación no respondió correctamente"

